//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampleHttpServer.Core.Api {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BankAccountsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BankAccountsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExampleHttpServer.Core.Api.BankAccountsResources", typeof(BankAccountsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;name&quot;: &quot;GR16 0110 1250 0000 0001 2300 695&quot;,
        ///        &quot;balance&quot;: &quot;$45,000&quot;,
        ///        &quot;interestRate&quot;: &quot;1.15%&quot;
        ///    },
        ///    {
        ///        &quot;name&quot;: &quot;GB29 NWBK 6016 1331 9268 19&quot;,
        ///        &quot;balance&quot;: &quot;$15,000&quot;,
        ///        &quot;interestRate&quot;: &quot;1.75%&quot;
        ///    },
        ///    {
        ///        &quot;name&quot;: &quot;SA03 8000 0000 6080 1016 7519&quot;,
        ///        &quot;balance&quot;: &quot;$150,000&quot;,
        ///        &quot;interestRate&quot;: &quot;2.45%&quot;
        ///    },
        ///    {
        ///        &quot;name&quot;: &quot;CH93 0076 2011 6238 5295 7&quot;,
        ///        &quot;balance&quot;: &quot;$5,000&quot;,
        ///        &quot;interestRate&quot;: &quot;1.05%&quot;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BankAccounts {
            get {
                return ResourceManager.GetString("BankAccounts", resourceCulture);
            }
        }
    }
}
